import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';
import sitemap from '@astrojs/sitemap';

// Keep in step with src/i18n/config.ts.
const defaultLocale = 'en';
const languages = { en: ['en'], 'pt-br': ['pt'], es: ['es'], he: ['he', 'iw'], ja: ['ja'] };
const htmlLang = { en: 'en', 'pt-br': 'pt-BR', es: 'es', he: 'he', ja: 'ja' };

/**
 * Writes Netlify's _redirects so a first visit lands on the visitor's language at the edge, with no flash:
 *   /install/  /pt-br/install/  302!  Language=pt
 * Netlify reads the browser's Accept-Language, and lets an `nf_lang` cookie override it. The language
 * switcher sets that cookie, so an explicit choice always wins. Crawlers send no Accept-Language and get English.
 */
const languageRedirects = () => ({
  name: 'language-redirects',
  hooks: {
    'astro:build:done': ({ dir, pages }) => {
      const others = Object.keys(languages).filter((l) => l !== defaultLocale);
      const isLocalized = (p) => others.some((l) => p === `${l}/` || p.startsWith(`${l}/`));
      const english = pages.map((p) => p.pathname).filter((p) => !isLocalized(p) && !p.startsWith('404'));
      const lines = ['# Generated by astro.config.mjs at build time. Do not edit.'];
      for (const l of others) {
        for (const p of english) lines.push(`/${p}  /${l}/${p}  302!  Language=${languages[l].join(',')}`);
        lines.push(`/${l}/*  /${l}/404/index.html  404`);
      }
      lines.push('/*  /404/index.html  404');
      writeFileSync(fileURLToPath(new URL('_redirects', dir)), lines.join('\n') + '\n');
    },
  },
});

export default defineConfig({
  site: 'https://aimemory.io',
  trailingSlash: 'always',
  i18n: { defaultLocale, locales: Object.keys(languages), routing: { prefixDefaultLocale: false } },
  integrations: [
    sitemap({ i18n: { defaultLocale, locales: htmlLang }, filter: (page) => !page.includes('/404') }),
    languageRedirects(),
  ],
  vite: { plugins: [tailwindcss()] },
  build: { inlineStylesheets: 'auto' },
});
